<?php

namespace Blamodex\Address\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AdministrativeAreaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // G20 nations: US, CA, MX, BR, AR, UK, DE, FR, IT, EU, RU, TR, SA, ZA, IN, CN, JP, KR, AU, ID
            $administrativeAreas = [
            // United States (US)
            ['country_code' => 'US', 'administrative_area' => 'Alabama', 'administrative_area_code' => 'AL'],
            ['country_code' => 'US', 'administrative_area' => 'Alaska', 'administrative_area_code' => 'AK'],
            ['country_code' => 'US', 'administrative_area' => 'Arizona', 'administrative_area_code' => 'AZ'],
            ['country_code' => 'US', 'administrative_area' => 'Arkansas', 'administrative_area_code' => 'AR'],
            ['country_code' => 'US', 'administrative_area' => 'California', 'administrative_area_code' => 'CA'],
            ['country_code' => 'US', 'administrative_area' => 'Colorado', 'administrative_area_code' => 'CO'],
            ['country_code' => 'US', 'administrative_area' => 'Connecticut', 'administrative_area_code' => 'CT'],
            ['country_code' => 'US', 'administrative_area' => 'Delaware', 'administrative_area_code' => 'DE'],
            ['country_code' => 'US', 'administrative_area' => 'Florida', 'administrative_area_code' => 'FL'],
            ['country_code' => 'US', 'administrative_area' => 'Georgia', 'administrative_area_code' => 'GA'],
            ['country_code' => 'US', 'administrative_area' => 'Hawaii', 'administrative_area_code' => 'HI'],
            ['country_code' => 'US', 'administrative_area' => 'Idaho', 'administrative_area_code' => 'ID'],
            ['country_code' => 'US', 'administrative_area' => 'Illinois', 'administrative_area_code' => 'IL'],
            ['country_code' => 'US', 'administrative_area' => 'Indiana', 'administrative_area_code' => 'IN'],
            ['country_code' => 'US', 'administrative_area' => 'Iowa', 'administrative_area_code' => 'IA'],
            ['country_code' => 'US', 'administrative_area' => 'Kansas', 'administrative_area_code' => 'KS'],
            ['country_code' => 'US', 'administrative_area' => 'Kentucky', 'administrative_area_code' => 'KY'],
            ['country_code' => 'US', 'administrative_area' => 'Louisiana', 'administrative_area_code' => 'LA'],
            ['country_code' => 'US', 'administrative_area' => 'Maine', 'administrative_area_code' => 'ME'],
            ['country_code' => 'US', 'administrative_area' => 'Maryland', 'administrative_area_code' => 'MD'],
            ['country_code' => 'US', 'administrative_area' => 'Massachusetts', 'administrative_area_code' => 'MA'],
            ['country_code' => 'US', 'administrative_area' => 'Michigan', 'administrative_area_code' => 'MI'],
            ['country_code' => 'US', 'administrative_area' => 'Minnesota', 'administrative_area_code' => 'MN'],
            ['country_code' => 'US', 'administrative_area' => 'Mississippi', 'administrative_area_code' => 'MS'],
            ['country_code' => 'US', 'administrative_area' => 'Missouri', 'administrative_area_code' => 'MO'],
            ['country_code' => 'US', 'administrative_area' => 'Montana', 'administrative_area_code' => 'MT'],
            ['country_code' => 'US', 'administrative_area' => 'Nebraska', 'administrative_area_code' => 'NE'],
            ['country_code' => 'US', 'administrative_area' => 'Nevada', 'administrative_area_code' => 'NV'],
            ['country_code' => 'US', 'administrative_area' => 'New Hampshire', 'administrative_area_code' => 'NH'],
            ['country_code' => 'US', 'administrative_area' => 'New Jersey', 'administrative_area_code' => 'NJ'],
            ['country_code' => 'US', 'administrative_area' => 'New Mexico', 'administrative_area_code' => 'NM'],
            ['country_code' => 'US', 'administrative_area' => 'New York', 'administrative_area_code' => 'NY'],
            ['country_code' => 'US', 'administrative_area' => 'North Carolina', 'administrative_area_code' => 'NC'],
            ['country_code' => 'US', 'administrative_area' => 'North Dakota', 'administrative_area_code' => 'ND'],
            ['country_code' => 'US', 'administrative_area' => 'Ohio', 'administrative_area_code' => 'OH'],
            ['country_code' => 'US', 'administrative_area' => 'Oklahoma', 'administrative_area_code' => 'OK'],
            ['country_code' => 'US', 'administrative_area' => 'Oregon', 'administrative_area_code' => 'OR'],
            ['country_code' => 'US', 'administrative_area' => 'Pennsylvania', 'administrative_area_code' => 'PA'],
            ['country_code' => 'US', 'administrative_area' => 'Rhode Island', 'administrative_area_code' => 'RI'],
            ['country_code' => 'US', 'administrative_area' => 'South Carolina', 'administrative_area_code' => 'SC'],
            ['country_code' => 'US', 'administrative_area' => 'South Dakota', 'administrative_area_code' => 'SD'],
            ['country_code' => 'US', 'administrative_area' => 'Tennessee', 'administrative_area_code' => 'TN'],
            ['country_code' => 'US', 'administrative_area' => 'Texas', 'administrative_area_code' => 'TX'],
            ['country_code' => 'US', 'administrative_area' => 'Utah', 'administrative_area_code' => 'UT'],
            ['country_code' => 'US', 'administrative_area' => 'Vermont', 'administrative_area_code' => 'VT'],
            ['country_code' => 'US', 'administrative_area' => 'Virginia', 'administrative_area_code' => 'VA'],
            ['country_code' => 'US', 'administrative_area' => 'Washington', 'administrative_area_code' => 'WA'],
            ['country_code' => 'US', 'administrative_area' => 'West Virginia', 'administrative_area_code' => 'WV'],
            ['country_code' => 'US', 'administrative_area' => 'Wisconsin', 'administrative_area_code' => 'WI'],
            ['country_code' => 'US', 'administrative_area' => 'Wyoming', 'administrative_area_code' => 'WY'],
            // Canada (CA)
            ['country_code' => 'CA', 'administrative_area' => 'Alberta', 'administrative_area_code' => 'AB'],
            ['country_code' => 'CA', 'administrative_area' => 'British Columbia', 'administrative_area_code' => 'BC'],
            ['country_code' => 'CA', 'administrative_area' => 'Manitoba', 'administrative_area_code' => 'MB'],
            ['country_code' => 'CA', 'administrative_area' => 'New Brunswick', 'administrative_area_code' => 'NB'],
            ['country_code' => 'CA', 'administrative_area' => 'Newfoundland and Labrador', 'administrative_area_code' => 'NL'],
            ['country_code' => 'CA', 'administrative_area' => 'Nova Scotia', 'administrative_area_code' => 'NS'],
            ['country_code' => 'CA', 'administrative_area' => 'Ontario', 'administrative_area_code' => 'ON'],
            ['country_code' => 'CA', 'administrative_area' => 'Prince Edward Island', 'administrative_area_code' => 'PE'],
            ['country_code' => 'CA', 'administrative_area' => 'Quebec', 'administrative_area_code' => 'QC'],
            ['country_code' => 'CA', 'administrative_area' => 'Saskatchewan', 'administrative_area_code' => 'SK'],
            ['country_code' => 'CA', 'administrative_area' => 'Northwest Territories', 'administrative_area_code' => 'NT'],
            ['country_code' => 'CA', 'administrative_area' => 'Nunavut', 'administrative_area_code' => 'NU'],
            ['country_code' => 'CA', 'administrative_area' => 'Yukon', 'administrative_area_code' => 'YT'],
            // Mexico (MX)
            ['country_code' => 'MX', 'administrative_area' => 'Aguascalientes', 'administrative_area_code' => 'AGU'],
            ['country_code' => 'MX', 'administrative_area' => 'Baja California', 'administrative_area_code' => 'BCN'],
            ['country_code' => 'MX', 'administrative_area' => 'Baja California Sur', 'administrative_area_code' => 'BCS'],
            ['country_code' => 'MX', 'administrative_area' => 'Campeche', 'administrative_area_code' => 'CAM'],
            ['country_code' => 'MX', 'administrative_area' => 'Chiapas', 'administrative_area_code' => 'CHP'],
            ['country_code' => 'MX', 'administrative_area' => 'Chihuahua', 'administrative_area_code' => 'CHH'],
            ['country_code' => 'MX', 'administrative_area' => 'Coahuila', 'administrative_area_code' => 'COA'],
            ['country_code' => 'MX', 'administrative_area' => 'Colima', 'administrative_area_code' => 'COL'],
            ['country_code' => 'MX', 'administrative_area' => 'Durango', 'administrative_area_code' => 'DUR'],
            ['country_code' => 'MX', 'administrative_area' => 'Guanajuato', 'administrative_area_code' => 'GUA'],
            ['country_code' => 'MX', 'administrative_area' => 'Guerrero', 'administrative_area_code' => 'GRO'],
            ['country_code' => 'MX', 'administrative_area' => 'Hidalgo', 'administrative_area_code' => 'HID'],
            ['country_code' => 'MX', 'administrative_area' => 'Jalisco', 'administrative_area_code' => 'JAL'],
            ['country_code' => 'MX', 'administrative_area' => 'Mexico State', 'administrative_area_code' => 'MEX'],
            ['country_code' => 'MX', 'administrative_area' => 'Michoacán', 'administrative_area_code' => 'MIC'],
            ['country_code' => 'MX', 'administrative_area' => 'Morelos', 'administrative_area_code' => 'MOR'],
            ['country_code' => 'MX', 'administrative_area' => 'Nayarit', 'administrative_area_code' => 'NAY'],
            ['country_code' => 'MX', 'administrative_area' => 'Nuevo León', 'administrative_area_code' => 'NLE'],
            ['country_code' => 'MX', 'administrative_area' => 'Oaxaca', 'administrative_area_code' => 'OAX'],
            ['country_code' => 'MX', 'administrative_area' => 'Puebla', 'administrative_area_code' => 'PUE'],
            ['country_code' => 'MX', 'administrative_area' => 'Querétaro', 'administrative_area_code' => 'QUE'],
            ['country_code' => 'MX', 'administrative_area' => 'Quintana Roo', 'administrative_area_code' => 'ROO'],
            ['country_code' => 'MX', 'administrative_area' => 'San Luis Potosí', 'administrative_area_code' => 'SLP'],
            ['country_code' => 'MX', 'administrative_area' => 'Sinaloa', 'administrative_area_code' => 'SIN'],
            ['country_code' => 'MX', 'administrative_area' => 'Sonora', 'administrative_area_code' => 'SON'],
            ['country_code' => 'MX', 'administrative_area' => 'Tabasco', 'administrative_area_code' => 'TAB'],
            ['country_code' => 'MX', 'administrative_area' => 'Tamaulipas', 'administrative_area_code' => 'TAM'],
            ['country_code' => 'MX', 'administrative_area' => 'Tlaxcala', 'administrative_area_code' => 'TLA'],
            ['country_code' => 'MX', 'administrative_area' => 'Veracruz', 'administrative_area_code' => 'VER'],
            ['country_code' => 'MX', 'administrative_area' => 'Yucatán', 'administrative_area_code' => 'YUC'],
            ['country_code' => 'MX', 'administrative_area' => 'Zacatecas', 'administrative_area_code' => 'ZAC'],
            // Brazil (BR)
            ['country_code' => 'BR', 'administrative_area' => 'Acre', 'administrative_area_code' => 'AC'],
            ['country_code' => 'BR', 'administrative_area' => 'Alagoas', 'administrative_area_code' => 'AL'],
            ['country_code' => 'BR', 'administrative_area' => 'Amapá', 'administrative_area_code' => 'AP'],
            ['country_code' => 'BR', 'administrative_area' => 'Amazonas', 'administrative_area_code' => 'AM'],
            ['country_code' => 'BR', 'administrative_area' => 'Bahia', 'administrative_area_code' => 'BA'],
            ['country_code' => 'BR', 'administrative_area' => 'Ceará', 'administrative_area_code' => 'CE'],
            ['country_code' => 'BR', 'administrative_area' => 'Distrito Federal', 'administrative_area_code' => 'DF'],
            ['country_code' => 'BR', 'administrative_area' => 'Espírito Santo', 'administrative_area_code' => 'ES'],
            ['country_code' => 'BR', 'administrative_area' => 'Goiás', 'administrative_area_code' => 'GO'],
            ['country_code' => 'BR', 'administrative_area' => 'Maranhão', 'administrative_area_code' => 'MA'],
            ['country_code' => 'BR', 'administrative_area' => 'Mato Grosso', 'administrative_area_code' => 'MT'],
            ['country_code' => 'BR', 'administrative_area' => 'Mato Grosso do Sul', 'administrative_area_code' => 'MS'],
            ['country_code' => 'BR', 'administrative_area' => 'Minas Gerais', 'administrative_area_code' => 'MG'],
            ['country_code' => 'BR', 'administrative_area' => 'Pará', 'administrative_area_code' => 'PA'],
            ['country_code' => 'BR', 'administrative_area' => 'Paraíba', 'administrative_area_code' => 'PB'],
            ['country_code' => 'BR', 'administrative_area' => 'Paraná', 'administrative_area_code' => 'PR'],
            ['country_code' => 'BR', 'administrative_area' => 'Pernambuco', 'administrative_area_code' => 'PE'],
            ['country_code' => 'BR', 'administrative_area' => 'Piauí', 'administrative_area_code' => 'PI'],
            ['country_code' => 'BR', 'administrative_area' => 'Rio de Janeiro', 'administrative_area_code' => 'RJ'],
            ['country_code' => 'BR', 'administrative_area' => 'Rio Grande do Norte', 'administrative_area_code' => 'RN'],
            ['country_code' => 'BR', 'administrative_area' => 'Rio Grande do Sul', 'administrative_area_code' => 'RS'],
            ['country_code' => 'BR', 'administrative_area' => 'Rondônia', 'administrative_area_code' => 'RO'],
            ['country_code' => 'BR', 'administrative_area' => 'Roraima', 'administrative_area_code' => 'RR'],
            ['country_code' => 'BR', 'administrative_area' => 'Santa Catarina', 'administrative_area_code' => 'SC'],
            ['country_code' => 'BR', 'administrative_area' => 'São Paulo', 'administrative_area_code' => 'SP'],
            ['country_code' => 'BR', 'administrative_area' => 'Sergipe', 'administrative_area_code' => 'SE'],
            ['country_code' => 'BR', 'administrative_area' => 'Tocantins', 'administrative_area_code' => 'TO'],
            // Argentina (AR)
            ['country_code' => 'AR', 'administrative_area' => 'Buenos Aires', 'administrative_area_code' => 'B'],
            ['country_code' => 'AR', 'administrative_area' => 'Catamarca', 'administrative_area_code' => 'K'],
            ['country_code' => 'AR', 'administrative_area' => 'Chaco', 'administrative_area_code' => 'H'],
            ['country_code' => 'AR', 'administrative_area' => 'Chubut', 'administrative_area_code' => 'U'],
            ['country_code' => 'AR', 'administrative_area' => 'Córdoba', 'administrative_area_code' => 'X'],
            ['country_code' => 'AR', 'administrative_area' => 'Corrientes', 'administrative_area_code' => 'W'],
            ['country_code' => 'AR', 'administrative_area' => 'Entre Ríos', 'administrative_area_code' => 'E'],
            ['country_code' => 'AR', 'administrative_area' => 'Formosa', 'administrative_area_code' => 'P'],
            ['country_code' => 'AR', 'administrative_area' => 'Jujuy', 'administrative_area_code' => 'Y'],
            ['country_code' => 'AR', 'administrative_area' => 'La Pampa', 'administrative_area_code' => 'L'],
            ['country_code' => 'AR', 'administrative_area' => 'La Rioja', 'administrative_area_code' => 'F'],
            ['country_code' => 'AR', 'administrative_area' => 'Mendoza', 'administrative_area_code' => 'M'],
            ['country_code' => 'AR', 'administrative_area' => 'Misiones', 'administrative_area_code' => 'N'],
            ['country_code' => 'AR', 'administrative_area' => 'Neuquén', 'administrative_area_code' => 'Q'],
            ['country_code' => 'AR', 'administrative_area' => 'Río Negro', 'administrative_area_code' => 'R'],
            ['country_code' => 'AR', 'administrative_area' => 'Salta', 'administrative_area_code' => 'A'],
            ['country_code' => 'AR', 'administrative_area' => 'San Juan', 'administrative_area_code' => 'J'],
            ['country_code' => 'AR', 'administrative_area' => 'San Luis', 'administrative_area_code' => 'D'],
            ['country_code' => 'AR', 'administrative_area' => 'Santa Cruz', 'administrative_area_code' => 'Z'],
            ['country_code' => 'AR', 'administrative_area' => 'Santa Fe', 'administrative_area_code' => 'S'],
            ['country_code' => 'AR', 'administrative_area' => 'Santiago del Estero', 'administrative_area_code' => 'G'],
            ['country_code' => 'AR', 'administrative_area' => 'Tierra del Fuego', 'administrative_area_code' => 'V'],
            ['country_code' => 'AR', 'administrative_area' => 'Tucumán', 'administrative_area_code' => 'T'],
            // United Kingdom (GB)
            ['country_code' => 'GB', 'administrative_area' => 'England', 'administrative_area_code' => 'ENG'],
            ['country_code' => 'GB', 'administrative_area' => 'Scotland', 'administrative_area_code' => 'SCT'],
            ['country_code' => 'GB', 'administrative_area' => 'Wales', 'administrative_area_code' => 'WLS'],
            ['country_code' => 'GB', 'administrative_area' => 'Northern Ireland', 'administrative_area_code' => 'NIR'],
            // Germany (DE)
            ['country_code' => 'DE', 'administrative_area' => 'Baden-Württemberg', 'administrative_area_code' => 'BW'],
            ['country_code' => 'DE', 'administrative_area' => 'Bavaria', 'administrative_area_code' => 'BY'],
            ['country_code' => 'DE', 'administrative_area' => 'Berlin', 'administrative_area_code' => 'BE'],
            ['country_code' => 'DE', 'administrative_area' => 'Brandenburg', 'administrative_area_code' => 'BB'],
            ['country_code' => 'DE', 'administrative_area' => 'Bremen', 'administrative_area_code' => 'HB'],
            ['country_code' => 'DE', 'administrative_area' => 'Hamburg', 'administrative_area_code' => 'HH'],
            ['country_code' => 'DE', 'administrative_area' => 'Hesse', 'administrative_area_code' => 'HE'],
            ['country_code' => 'DE', 'administrative_area' => 'Lower Saxony', 'administrative_area_code' => 'NI'],
            ['country_code' => 'DE', 'administrative_area' => 'Mecklenburg-Vorpommern', 'administrative_area_code' => 'MV'],
            ['country_code' => 'DE', 'administrative_area' => 'North Rhine-Westphalia', 'administrative_area_code' => 'NW'],
            ['country_code' => 'DE', 'administrative_area' => 'Rhineland-Palatinate', 'administrative_area_code' => 'RP'],
            ['country_code' => 'DE', 'administrative_area' => 'Saarland', 'administrative_area_code' => 'SL'],
            ['country_code' => 'DE', 'administrative_area' => 'Saxony', 'administrative_area_code' => 'SN'],
            ['country_code' => 'DE', 'administrative_area' => 'Saxony-Anhalt', 'administrative_area_code' => 'ST'],
            ['country_code' => 'DE', 'administrative_area' => 'Schleswig-Holstein', 'administrative_area_code' => 'SH'],
            ['country_code' => 'DE', 'administrative_area' => 'Thuringia', 'administrative_area_code' => 'TH'],
            // France (FR)
            ['country_code' => 'FR', 'administrative_area' => 'Auvergne-Rhône-Alpes', 'administrative_area_code' => 'ARA'],
            ['country_code' => 'FR', 'administrative_area' => 'Bourgogne-Franche-Comté', 'administrative_area_code' => 'BFC'],
            ['country_code' => 'FR', 'administrative_area' => 'Brittany', 'administrative_area_code' => 'BRE'],
            ['country_code' => 'FR', 'administrative_area' => 'Centre-Val de Loire', 'administrative_area_code' => 'CVL'],
            ['country_code' => 'FR', 'administrative_area' => 'Corsica', 'administrative_area_code' => 'COR'],
            ['country_code' => 'FR', 'administrative_area' => 'Grand Est', 'administrative_area_code' => 'GES'],
            ['country_code' => 'FR', 'administrative_area' => 'Hauts-de-France', 'administrative_area_code' => 'HDF'],
            ['country_code' => 'FR', 'administrative_area' => 'Île-de-France', 'administrative_area_code' => 'IDF'],
            ['country_code' => 'FR', 'administrative_area' => 'Normandy', 'administrative_area_code' => 'NOR'],
            ['country_code' => 'FR', 'administrative_area' => 'Nouvelle-Aquitaine', 'administrative_area_code' => 'NAQ'],
            ['country_code' => 'FR', 'administrative_area' => 'Occitanie', 'administrative_area_code' => 'OCC'],
            ['country_code' => 'FR', 'administrative_area' => 'Pays de la Loire', 'administrative_area_code' => 'PDL'],
            ['country_code' => 'FR', 'administrative_area' => 'Provence-Alpes-Côte d\'Azur', 'administrative_area_code' => 'PAC'],
            // Italy (IT)
            ['country_code' => 'IT', 'administrative_area' => 'Abruzzo', 'administrative_area_code' => '65'],
            ['country_code' => 'IT', 'administrative_area' => 'Aosta Valley', 'administrative_area_code' => '23'],
            ['country_code' => 'IT', 'administrative_area' => 'Apulia', 'administrative_area_code' => '75'],
            ['country_code' => 'IT', 'administrative_area' => 'Basilicata', 'administrative_area_code' => '77'],
            ['country_code' => 'IT', 'administrative_area' => 'Calabria', 'administrative_area_code' => '78'],
            ['country_code' => 'IT', 'administrative_area' => 'Campania', 'administrative_area_code' => '72'],
            ['country_code' => 'IT', 'administrative_area' => 'Emilia-Romagna', 'administrative_area_code' => '45'],
            ['country_code' => 'IT', 'administrative_area' => 'Friuli Venezia Giulia', 'administrative_area_code' => '36'],
            ['country_code' => 'IT', 'administrative_area' => 'Lazio', 'administrative_area_code' => '62'],
            ['country_code' => 'IT', 'administrative_area' => 'Liguria', 'administrative_area_code' => '42'],
            ['country_code' => 'IT', 'administrative_area' => 'Lombardy', 'administrative_area_code' => '25'],
            ['country_code' => 'IT', 'administrative_area' => 'Marche', 'administrative_area_code' => '57'],
            ['country_code' => 'IT', 'administrative_area' => 'Molise', 'administrative_area_code' => '67'],
            ['country_code' => 'IT', 'administrative_area' => 'Piedmont', 'administrative_area_code' => '21'],
            ['country_code' => 'IT', 'administrative_area' => 'Sardinia', 'administrative_area_code' => '88'],
            ['country_code' => 'IT', 'administrative_area' => 'Sicily', 'administrative_area_code' => '82'],
            ['country_code' => 'IT', 'administrative_area' => 'Trentino-Alto Adige', 'administrative_area_code' => '32'],
            ['country_code' => 'IT', 'administrative_area' => 'Tuscany', 'administrative_area_code' => '52'],
            ['country_code' => 'IT', 'administrative_area' => 'Umbria', 'administrative_area_code' => '55'],
            ['country_code' => 'IT', 'administrative_area' => 'Veneto', 'administrative_area_code' => '34'],
            // Russia (RU)
            ['country_code' => 'RU', 'administrative_area' => 'Moscow', 'administrative_area_code' => 'MOW'],
            ['country_code' => 'RU', 'administrative_area' => 'Saint Petersburg', 'administrative_area_code' => 'SPE'],
            ['country_code' => 'RU', 'administrative_area' => 'Novosibirsk Oblast', 'administrative_area_code' => 'NVS'],
            ['country_code' => 'RU', 'administrative_area' => 'Krasnodar Krai', 'administrative_area_code' => 'KDA'],
            ['country_code' => 'RU', 'administrative_area' => 'Sverdlovsk Oblast', 'administrative_area_code' => 'SVE'],
            // Turkey (TR)
            ['country_code' => 'TR', 'administrative_area' => 'Ankara', 'administrative_area_code' => '06'],
            ['country_code' => 'TR', 'administrative_area' => 'Istanbul', 'administrative_area_code' => '34'],
            ['country_code' => 'TR', 'administrative_area' => 'Izmir', 'administrative_area_code' => '35'],
            // Saudi Arabia (SA)
            ['country_code' => 'SA', 'administrative_area' => 'Riyadh', 'administrative_area_code' => '01'],
            ['country_code' => 'SA', 'administrative_area' => 'Makkah', 'administrative_area_code' => '02'],
            ['country_code' => 'SA', 'administrative_area' => 'Eastern Province', 'administrative_area_code' => '04'],
            // South Africa (ZA)
            ['country_code' => 'ZA', 'administrative_area' => 'Gauteng', 'administrative_area_code' => 'GP'],
            ['country_code' => 'ZA', 'administrative_area' => 'Western Cape', 'administrative_area_code' => 'WC'],
            ['country_code' => 'ZA', 'administrative_area' => 'KwaZulu-Natal', 'administrative_area_code' => 'KZN'],
            // India (IN)
            ['country_code' => 'IN', 'administrative_area' => 'Andhra Pradesh', 'administrative_area_code' => 'AP'],
            ['country_code' => 'IN', 'administrative_area' => 'Arunachal Pradesh', 'administrative_area_code' => 'AR'],
            ['country_code' => 'IN', 'administrative_area' => 'Assam', 'administrative_area_code' => 'AS'],
            ['country_code' => 'IN', 'administrative_area' => 'Bihar', 'administrative_area_code' => 'BR'],
            ['country_code' => 'IN', 'administrative_area' => 'Chhattisgarh', 'administrative_area_code' => 'CT'],
            ['country_code' => 'IN', 'administrative_area' => 'Goa', 'administrative_area_code' => 'GA'],
            ['country_code' => 'IN', 'administrative_area' => 'Gujarat', 'administrative_area_code' => 'GJ'],
            ['country_code' => 'IN', 'administrative_area' => 'Haryana', 'administrative_area_code' => 'HR'],
            ['country_code' => 'IN', 'administrative_area' => 'Himachal Pradesh', 'administrative_area_code' => 'HP'],
            ['country_code' => 'IN', 'administrative_area' => 'Jharkhand', 'administrative_area_code' => 'JH'],
            ['country_code' => 'IN', 'administrative_area' => 'Karnataka', 'administrative_area_code' => 'KA'],
            ['country_code' => 'IN', 'administrative_area' => 'Kerala', 'administrative_area_code' => 'KL'],
            ['country_code' => 'IN', 'administrative_area' => 'Madhya Pradesh', 'administrative_area_code' => 'MP'],
            ['country_code' => 'IN', 'administrative_area' => 'Maharashtra', 'administrative_area_code' => 'MH'],
            ['country_code' => 'IN', 'administrative_area' => 'Manipur', 'administrative_area_code' => 'MN'],
            ['country_code' => 'IN', 'administrative_area' => 'Meghalaya', 'administrative_area_code' => 'ML'],
            ['country_code' => 'IN', 'administrative_area' => 'Mizoram', 'administrative_area_code' => 'MZ'],
            ['country_code' => 'IN', 'administrative_area' => 'Nagaland', 'administrative_area_code' => 'NL'],
            ['country_code' => 'IN', 'administrative_area' => 'Odisha', 'administrative_area_code' => 'OR'],
            ['country_code' => 'IN', 'administrative_area' => 'Punjab', 'administrative_area_code' => 'PB'],
            ['country_code' => 'IN', 'administrative_area' => 'Rajasthan', 'administrative_area_code' => 'RJ'],
            ['country_code' => 'IN', 'administrative_area' => 'Sikkim', 'administrative_area_code' => 'SK'],
            ['country_code' => 'IN', 'administrative_area' => 'Tamil Nadu', 'administrative_area_code' => 'TN'],
            ['country_code' => 'IN', 'administrative_area' => 'Telangana', 'administrative_area_code' => 'TG'],
            ['country_code' => 'IN', 'administrative_area' => 'Tripura', 'administrative_area_code' => 'TR'],
            ['country_code' => 'IN', 'administrative_area' => 'Uttar Pradesh', 'administrative_area_code' => 'UP'],
            ['country_code' => 'IN', 'administrative_area' => 'Uttarakhand', 'administrative_area_code' => 'UT'],
            ['country_code' => 'IN', 'administrative_area' => 'West Bengal', 'administrative_area_code' => 'WB'],
            // China (CN)
            ['country_code' => 'CN', 'administrative_area' => 'Beijing', 'administrative_area_code' => 'BJ'],
            ['country_code' => 'CN', 'administrative_area' => 'Shanghai', 'administrative_area_code' => 'SH'],
            ['country_code' => 'CN', 'administrative_area' => 'Guangdong', 'administrative_area_code' => 'GD'],
            ['country_code' => 'CN', 'administrative_area' => 'Sichuan', 'administrative_area_code' => 'SC'],
            ['country_code' => 'CN', 'administrative_area' => 'Yunnan', 'administrative_area_code' => 'YN'],
            // Japan (JP)
            ['country_code' => 'JP', 'administrative_area' => 'Tokyo', 'administrative_area_code' => '13'],
            ['country_code' => 'JP', 'administrative_area' => 'Osaka', 'administrative_area_code' => '27'],
            ['country_code' => 'JP', 'administrative_area' => 'Hokkaido', 'administrative_area_code' => '01'],
            ['country_code' => 'JP', 'administrative_area' => 'Aichi', 'administrative_area_code' => '23'],
            // South Korea (KR)
            ['country_code' => 'KR', 'administrative_area' => 'Seoul', 'administrative_area_code' => '11'],
            ['country_code' => 'KR', 'administrative_area' => 'Busan', 'administrative_area_code' => '26'],
            ['country_code' => 'KR', 'administrative_area' => 'Incheon', 'administrative_area_code' => '28'],
            // Australia (AU)
            ['country_code' => 'AU', 'administrative_area' => 'New South Wales', 'administrative_area_code' => 'NSW'],
            ['country_code' => 'AU', 'administrative_area' => 'Victoria', 'administrative_area_code' => 'VIC'],
            ['country_code' => 'AU', 'administrative_area' => 'Queensland', 'administrative_area_code' => 'QLD'],
            ['country_code' => 'AU', 'administrative_area' => 'Western Australia', 'administrative_area_code' => 'WA'],
            ['country_code' => 'AU', 'administrative_area' => 'South Australia', 'administrative_area_code' => 'SA'],
            ['country_code' => 'AU', 'administrative_area' => 'Tasmania', 'administrative_area_code' => 'TAS'],
            ['country_code' => 'AU', 'administrative_area' => 'Australian Capital Territory', 'administrative_area_code' => 'ACT'],
            ['country_code' => 'AU', 'administrative_area' => 'Northern Territory', 'administrative_area_code' => 'NT'],
            // Indonesia (ID)
            ['country_code' => 'ID', 'administrative_area' => 'Jakarta', 'administrative_area_code' => 'JK'],
            ['country_code' => 'ID', 'administrative_area' => 'West Java', 'administrative_area_code' => 'JB'],
            ['country_code' => 'ID', 'administrative_area' => 'Central Java', 'administrative_area_code' => 'JT'],
            ['country_code' => 'ID', 'administrative_area' => 'East Java', 'administrative_area_code' => 'JI'],
            ['country_code' => 'ID', 'administrative_area' => 'Bali', 'administrative_area_code' => 'BA'],
        ];

        // Get country_id for each country_code
            $countryIds = DB::table('countries')->pluck('id', 'country_code');
            $now = now();
            $rows = [];
            foreach ($administrativeAreas as $area) {
                $country_id = $countryIds[$area['country_code']] ?? null;
                if ($country_id) {
                    $rows[] = [
                        'uuid' => Str::uuid()->toString(),
                        'country_id' => $country_id,
                        'administrative_area' => $area['administrative_area'],
                        'administrative_area_code' => $area['administrative_area_code'],
                        'created_at' => $now,
                        'updated_at' => $now,
                    ];
                }
            }
            if ($rows) {
                DB::table('administrative_areas')->upsert(
                    $rows,
                    ['country_id', 'administrative_area_code'],
                    ['administrative_area', 'updated_at']
                );
            }
    }
}
